### ISSUE TITLE
Change mode order (details inside)

### ISSUE THREAD

**Issue by Dacvak** [cnlohr/swadge2019#11]
Swap Light Dances with D6 mode.

Final mode order should be:
Mode 1: Color Chord
Mode 2: Reflector Game
Mode 3: Light Dances
Mode 4: D6
Mode 5: Flashlight
Mode 6: Tuner

**Comment by thaeli** [comment]
I concur with this mode order.

**Comment by AEFeinstein** [comment]
So it is written, so it shall be done.
